services:
  ollama:
    image: ollama/ollama:0.30.5
    ports:
      - "11434:11434"
  kotlin:
    build: ../zad3
    ports:
      - "8080:8080"
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
      - PYTHON_SERVICE_URL=http://python:8000
    depends_on:
      - ollama
  python:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - kotlin
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
